### ISSUE TITLE
<Layout>: move footer.o-typography-footer out of div.article-body?

### ISSUE THREAD

**Issue by davidbjourno** [Financial-Times/g-components#120]
Perhaps into a `div.article-footer` one level up in the tree? This would give us the option to portal things into `div.article-body` and have them be outside `<GridContainer>`.

**Comment by aendrew** [comment]
I don't think you can portal things into a React-rendered div? Portals are a very limited use-case. Is this mainly just to get the copyright notice outside of the article body, by moving it one level up? I'm not opposed to this, the only style change is adding a `.o-typography-wrapper` call to the footer.
